### ISSUE TITLE
Include custodian stake amount in voting and membership status

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdac-contracts#1]
Via Telegram
```
Michael Yeates admin, [Dec 19, 2018 at 2:20:33 PM]:
yeah - we probably should include them really
as well as for membership status
```

**Comment by michaeljyeates** [comment]
I think we should move responsibility for staking to the token contract

Benefits are

1. All membership statuses and voting when staked will just work without any special cases
2. Adding native staking capability along with observers for stake balance changes will allow us to be much more flexible in the future on voting strategies which can be enabled with configuration.
3. Custodian contract will still be in charge of if the tokens can be unstaked.  It will assert during the unstake observation to prevent it from executing.

Add the following actions to the token contract

`stake(name account, asset quantity)`

Will add an entry (or update existing one) to the `stakes` table. Will send a `stakeobsv` action to the custodian contract, or the vote weight contract if configured.

`unstake(name account, asset quantity)`

Will add an entry to the `unstakes` table with the unstake time and amount set.  Multiple entries are allowed per account.  The unstake time is calculated based on the account's `staketime` setting, if this is not set then it will fall back to the default time set in `stakeconfig`. Will send a `stakeobsv` action to the custodian contract, or the vote weight contract if configured.

`staketime(name account, uint32_t unstake_time)`

Will change the account's `staketime` parameter in the `staketimes` table.  If the new value is less than the current value then the account must unstake all existing stakes (ie. the stake table must be empty for that user).  If the value being set is less than the configured minimum value then it will fail.  A deferred transaction will be sent to `refund`.

`stakeconfig(stake_config config, symbol token_symbol)`

Updates the config which consists of `staking_enabled`, `default_time`, `min_time`, action must have permission of authority account of DAC derived from the symbol.

`refund(uint64_t unstake_id)`

Will remove tokens from the `unstaked` entry matching the unstake_id if the unstake time has passed.  Then it will subtract those number of tokens from the `stakes` table.  This action can either be called by deferred transaction or manually if that fails.

**Preventing staked transfers**

If staking is enabled then the token contract will check staked balance when making a transfer and will assert if the amount being transferred is greater than the balance minus the amount staked.

**Migration**

eosDAC should install the new contract and enable staking with a 3 day unstake time.  Then a new `migratestake` action which will transfer the stakes back to the users along with a `forcestake` action.  This is a temporary action added to the token contract which will stake the tokens and require authority of the authority account.

**Comment by dallasjohnson** [comment]
@michaeljyeates Interesting idea and could help encapsulate more token related logic into one place. Just to clarify: with the `stake` action you suggested that should add to an existing entry (if there is one) where would the stake release timestamp get saved then? Would that subsequent staking extend the initial stake timestamp out out for all staked tokens or would additional staked tokens adopt the initial stake timestamp (which may have already passed)? 

It feels like if you can stake more than once then a ledger of stakes would be needed which would contain `{"staker": "mrstaker", quantity": "5.0000 EOSDAC", "locked_until" : "6June2020" }` and then another simple table per user which could track the total staked amount used for vote_weight actions. which would be updated for each (un)stake action. Obviously this is pretty RAM hungry but each user may only have 1 entry for staking so it would most consuming for the required indices in the table to quickly access the required rows.

**Comment by michaeljyeates** [comment]
Yes, there is one stake entry per user and many potential unstake entries (but these will be short-lived)
