### ISSUE TITLE
Create flowchart for testing worker proposals

### ISSUE THREAD

**Issue by michaeljyeates** [eosdac/eosdac-contracts#105]
- [x] Create a flowchart to show all the states which need to be tested for the worker proposals to pass to testers
- [x] Needs to be deployed somewhere

**Comment by str** [comment]
flowchart at https://app.diagrams.net/#G1vqAlM1PRdC0uzp5IKcUiKHfPoDfAjhEI

**Comment by str** [comment]
![image](https://user-images.githubusercontent.com/123817/88665029-34a5a280-d09b-11ea-87f6-82e361bf46f0.png)

**Comment by str** [comment]
Flowchart ready. Now we need to make it public.  I'm on it.

**Comment by str** [comment]
released to https://github.com/eosdac/documentation/wiki/development
