### ISSUE TITLE
Standardize config table name across all contracts

### ISSUE THREAD

**Issue by dallasjohnson** [eosdac/eosdac-contracts#19]

**Comment by dallasjohnson** [comment]
This also involves migrating the existing data in the table and adapting the code to read from the new tables.

**Comment by piecesnbits** [comment]
cool, also it would be better to make the parameters from the updateconfig action the same. on dacproposals we have "new_config", on dacelections it is "newconfig".

**Comment by dallasjohnson** [comment]
Done
