### ISSUE TITLE
read config from custodian contract (jungle)

### ISSUE THREAD

**Issue by piecesnbits** [eosdac/eosdac-contracts#27]
500 error.
![image](https://user-images.githubusercontent.com/44613132/59934744-89183080-944c-11e9-9b1a-60ef59a25a84.png)

`>{"code":500,"message":"Internal Service Error","error":{"code":3010014,"name":"symbol_type_exception","what":"Invalid symbol","details":[{"message":"invalid symbol: \u000f\u0000\u0000\u0000\u0003","file":"symbol.hpp","line_number":142,"method":"reflector_init"},{"message":"error unpacking eosio::chain::symbol","file":"raw.hpp","line_number":644,"method":"unpack"},{"message":"Error unpacking field sym","file":"raw.hpp","line_number":367,"method":"operator()"},{"message":"error unpacking eosio::chain::asset","file":"raw.hpp","line_number":644,"method":"unpack"},{"message":"Unable to unpack built-in type 'asset' while processing 'contr_config.requested_pay_max'","file":"abi_serializer.cpp","line_number":327,"method":"_binary_to_variant"}]}}`

**Comment by piecesnbits** [comment]
although the table is scoped
![image](https://user-images.githubusercontent.com/44613132/59934898-e613e680-944c-11e9-9b19-3592cbbedca6.png)

**Comment by dallasjohnson** [comment]
This is not a contract issue. This is because the contract was updated without migrating the table first. To fix it an older version of the code (pre-scope migration) needs to be deployed to Jungle.
