### ISSUE TITLE
Deploy WP contracts to mainnet

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdac-contracts#76]
1. Check which contracts were modified
2. Put up msigs.
3. Relies on https://github.com/eosdac/eosdac-contracts/issues/75
4. When tested, deploy new client: https://github.com/eosdac/eosdac-client/issues/22

**Comment by str** [comment]
I'm going to close this issue as "deploying" is a step in the kanban/project board instead of something by itself.
