### ISSUE TITLE
Unable to Reg Candidate on eosDAC or KROWN DAC

### ISSUE THREAD

**Issue by maximusmaximus** [eosdac/eosdac-contracts#95]
Recreated across multiple wallets and with multiple users.
![image](https://user-images.githubusercontent.com/15719015/80256254-5114e780-8633-11ea-993a-c0543edd1e6e.png)

**Comment by lukestokes** [comment]
@michaeljyeates or @dallasjohnson do you know what causes this?

**Comment by lukestokes** [comment]
Confirmed this is fixed as long as you have the latest contracts deployed and the correct link authorizations.

**Comment by lukestokes** [comment]
daccustodian::balanceobsv
daccustodian::capturestake
daccustodian::stakeobsv
daccustodian::transferobsv
